import 'package:get/get.dart';

class Localization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'es': {
          'auth.signInButton': 'Iniciar sesión',
          'auth.signUpButton': 'Inscribirse',
          'auth.resetPasswordButton': 'Enviar restablecimiento de contraseña',
          'auth.emailFormField': 'Correo electrónico',
          'auth.passwordFormField': 'Contraseña',
          'auth.nameFormField': 'Nombre',
          'auth.signInErrorTitle': 'Error',
          'auth.signInError':
              'Error de inicio de sesión: correo electrónico o contraseña incorrecta.',
          'auth.resetPasswordLabelButton': '¿Se te olvidó tu contraseña?',
          'auth.signUpLabelButton': 'Crea una cuenta',
          'auth.signUpErrorTitle': 'Registro fallido.',
          'auth.signUpError':
              'Hubo un problema registrándolo. Por favor, inténtelo de nuevo más tarde.',
          'auth.signInLabelButton': '¿Tener una cuenta? Iniciar sesión.',
          'auth.resetPasswordNoticeTitle':
              'Restablecimiento de contraseña Correo electrónico enviado',
          'auth.resetPasswordNotice':
              'Revise su correo electrónico y siga las instrucciones para restablecer su contraseña.',
          'auth.resetPasswordFailed':
              'Falló el correo electrónico de restablecimiento de la contraseña',
          'auth.signInonResetPasswordLabelButton': 'Iniciar sesión',
          'auth.updateUser': 'Actualización del perfil',
          'auth.updateUserSuccessNoticeTitle': 'Usuario actualizado',
          'auth.updateUserSuccessNotice':
              'Información del usuario actualizada con éxito.',
          'auth.updateUserEmailInUse':
              'Esa dirección de correo electrónico ya tiene una cuenta.',
          'auth.updateUserFailNotice': 'Error al actualizar el usuario',
          'auth.enterPassword': 'Ingresa tu contraseña',
          'auth.cancel': 'Cancelar',
          'auth.submit': 'Enviar',
          'auth.changePasswordLabelButton': 'Cambiar la contraseña',
          'auth.resetPasswordTitle': 'Restablecer la contraseña',
          'auth.updateProfileTitle': 'Actualización del perfil',
          'auth.wrongPasswordNoticeTitle': 'Error de inicio de sesion',
          'auth.wrongPasswordNotice':
              'La contraseña no coincide con nuestros registros.',
          'auth.unknownError': 'Error desconocido',
          'settings.title': 'Ajustes',
          'settings.language': 'Idioma',
          'settings.theme': 'Tema',
          'settings.signOut': 'Desconectar',
          'settings.dark': 'Oscuro',
          'settings.light': 'Luz',
          'settings.system': 'Sistema',
          'settings.updateProfile': 'Actualización del perfil',
          'home.title': 'Casa',
          'home.nameLabel': 'Nombre',
          'home.uidLabel': 'Uid',
          'home.emailLabel': 'Correo electrónico',
          'home.adminUserLabel': 'Administrador',
          'app.title': 'Proyecto de inicio de aleteador',
          'validator.email':
              'Por favor, introduce una dirección de correo electrónico válida.',
          'validator.password':
              'La contraseña debe tener al menos 6 caracteres.',
          'validator.name': 'Por favor ingrese un nombre.',
          'validator.number': 'Por favor, introduzca un número.',
          'validator.notEmpty': 'Este es un campo obligatorio.',
          'validator.amount':
              'Por favor ingrese un número I.E. 250 - Sin símbolo de dólar y sin centavos',
          'general.title': 'Cuentas',
          'general.january': 'Enero',
          'general.february': 'Febrero',
          'general.march': 'Marzo',
          'general.april': 'Abril',
          'general.may': 'Mayo',
          'general.june': 'Junio',
          'general.july': 'Julio',
          'general.august': 'Agosto',
          'general.september': 'Septiembre',
          'general.october': 'Octubre',
          'general.november': 'Noviembre',
          'general.december': 'Diciembre',
          'general.total': 'Total',
          'general.selectAll': 'Seleccionar Todo',
          'general.selectowner': 'Seleccionar Propietario',
          'general.amount': 'Monto',
          'general.cancel': 'Cancelar',
          'general.accept': 'Aceptar',
          'general.noData': 'Sin Datos',
          'general.filter': 'Filtro',
          'general.titleOK': 'Correcto',
          'general.titleNoOK': 'Error',
          'general.messageOK': 'Todo Salio Correcto',
          'general.messageNoOK': 'Error en el proceso',
          'chart.title': 'Gráficos',
          'chart.monthly': 'Gráfico Mensual',
          'chart.accounts': 'Gráfico Cuentas',
          'accounts.title': 'Cuentas',
          'accounts.insert': 'Insertar',
          'accounts.delete': 'Eliminar',
          'accounts.questionInsert': '¿Desea Insertar?',
          'accounts.questionDelete': '¿Desea eliminar?',
          'password.title': 'Claves',
          'password.name': 'Nombre',
          'password.user': 'Usuario',
          'password.email': 'Email',
          'password.password': 'Clave',
          'password.details': 'Detalle',
        },
        'en': {
          'auth.signInButton': 'Log in',
          'auth.signUpButton': 'Register',
          'auth.resetPasswordButton': 'Send reset password',
          'auth.emailFormField': 'Email',
          'auth.passwordFormField': 'Password',
          'auth.nameFormField': 'Name',
          'auth.signInErrorTitle': 'Error',
          'auth.signInError': 'Logon error: Email or incorrect password.',
          'auth.resetPasswordLabelButton': 'Did you forget your password?',
          'auth.signUpLabelButton': 'Create an account',
          'auth.signUpErrorTitle': 'Sign up failed.',
          'auth.signUpError':
              'There was a problem registering it. Please try again later.',
          'auth.signInLabelButton': 'Have an account? Log in.',
          'auth.resetPasswordNoticeTitle': 'Password restoration Email sent',
          'auth.resetPasswordNotice':
              'Review your email and follow the instructions to reset your password.',
          'auth.resetPasswordFailed': 'The password restoration email failed',
          'auth.signInonResetPasswordLabelButton': 'Log in',
          'auth.updateUser': 'Profile update',
          'auth.updateUserSuccessNoticeTitle': 'Updated User.',
          'auth.updateUserSuccessNotice':
              'User information updated successfully.',
          'auth.updateUserEmailInUse':
              'That email address already has an account.',
          'auth.updateUserFailNotice': 'Error updating the user',
          'auth.enterPassword': 'Enter your password.',
          'auth.cancel': 'Cancel',
          'auth.submit': 'Send',
          'auth.changePasswordLabelButton': 'Change Password',
          'auth.resetPasswordTitle': 'Reset your password',
          'auth.updateProfileTitle': 'Profile update',
          'auth.wrongPasswordNoticeTitle': 'Login error',
          'auth.wrongPasswordNotice':
              'The password does not match our records.',
          'auth.unknownError': 'Unknown error',
          'settings.title': 'Settings',
          'settings.language': 'Idiom',
          'settings.theme': 'Theme',
          'settings.signOut': 'Disconnect',
          'settings.dark': 'Dark',
          'settings.light': 'Light',
          'settings.system': 'System',
          'settings.updateProfile': 'Profile update',
          'home.title': 'Home',
          'home.nameLabel': 'Name',
          'home.uidLabel': 'Uid.',
          'home.emailLabel': 'Email',
          'home.adminUserLabel': 'Administrator',
          'app.title': 'Floor start project',
          'validator.email': 'Please enter a valid email address.',
          'validator.password': 'The password must be at least 6 characters.',
          'validator.name': 'Please enter a name.',
          'validator.number': 'Please enter a number.',
          'validator.notEmpty': 'This is a mandatory field.',
          'validator.amount':
              'Please enter a number i.e. 250 - No symbol of dollar and without cents',
          'general.title': 'Accounts',
          'general.january': 'January',
          'general.february': 'February',
          'general.march': 'March',
          'general.april': 'April',
          'general.may': 'May',
          'general.june': 'June',
          'general.july': 'July',
          'general.august': 'August',
          'general.september': 'September',
          'general.october': 'October',
          'general.november': 'November',
          'general.december': 'December',
          'general.total': 'Total',
          'general.selectAll': 'Select all',
          'general.selectowner': 'Select owner',
          'general.amount': 'Amount',
          'general.cancel': 'Cancel',
          'general.accept': 'To accept',
          'chart.title': 'Graphics',
          'chart.monthly': 'Monthly graphic',
          'chart.accounts': 'Graph Accounts',
          'accounts.title': 'Accounts',
          'accounts.insert': 'Insert',
          'accounts.delete': 'Get rid of',
          'accounts.questionInsert': 'Do you want to insert?',
          'accounts.questionDelete': 'Do you want to delete?',
        },
        'fr': {
          'auth.signInButton': 'Commencer la session',
          'auth.signUpButton': 'S\'inscrire',
          'auth.resetPasswordButton':
              'Envoyer un mot de passe de réinitialisation',
          'auth.emailFormField': 'Courrier électronique',
          'auth.passwordFormField': 'Mot de passe',
          'auth.nameFormField': 'nom',
          'auth.signInErrorTitle': 'Erreur',
          'auth.signInError':
              'Erreur de connexion: email ou mot de passe incorrect.',
          'auth.resetPasswordLabelButton':
              'Avez-vous oublié votre mot de passe?',
          'auth.signUpLabelButton': 'Créer un compte',
          'auth.signUpErrorTitle': 'Inscrivez-vous échoué.',
          'auth.signUpError':
              'Il y avait un problème qui l\'enregistrait. Veuillez réessayer plus tard.',
          'auth.signInLabelButton': 'Avoir un compte? Commencer la session.',
          'auth.resetPasswordNoticeTitle':
              'Mot de passe Restauration Email envoyé',
          'auth.resetPasswordNotice':
              'Examinez votre email et suivez les instructions pour réinitialiser votre mot de passe.',
          'auth.resetPasswordFailed':
              'L\'e-mail de restauration de mot de passe a échoué',
          'auth.signInonResetPasswordLabelButton': 'Commencer la session',
          'auth.updateUser': 'Mise à jour du profil',
          'auth.updateUserSuccessNoticeTitle': 'Utilisateur mis à jour.',
          'auth.updateUserSuccessNotice':
              'Informations de l\'utilisateur mis à jour avec succès.',
          'auth.updateUserEmailInUse':
              'Cette adresse électronique a déjà un compte.',
          'auth.updateUserFailNotice':
              'Erreur lors de la mise à jour de l\'utilisateur',
          'auth.enterPassword': 'Tapez votre mot de passe.',
          'auth.cancel': 'Annuler',
          'auth.submit': 'Envoyer',
          'auth.changePasswordLabelButton': 'Changer le mot de passe',
          'auth.resetPasswordTitle': 'réinitialisez votre mot de passe',
          'auth.updateProfileTitle': 'Mise à jour du profil',
          'auth.wrongPasswordNoticeTitle': 'Erreur d\'identification',
          'auth.wrongPasswordNotice':
              'Le mot de passe ne correspond pas à nos enregistrements.',
          'auth.unknownError': 'Erreur inconnue',
          'settings.title': 'Paramètres',
          'settings.language': 'langage',
          'settings.theme': 'Thème',
          'settings.signOut': 'Déconnecter',
          'settings.dark': 'Sombre',
          'settings.light': 'Lumière',
          'settings.system': 'Système',
          'settings.updateProfile': 'Mise à jour du profil',
          'home.title': 'Maison',
          'home.nameLabel': 'nom',
          'home.uidLabel': 'UID.',
          'home.emailLabel': 'Courrier électronique',
          'home.adminUserLabel': 'Administrateur',
          'app.title': 'Projet de départ du sol',
          'validator.email':
              'S\'il vous plaît, mettez une adresse email valide.',
          'validator.password':
              'Le mot de passe doit comporter au moins 6 caractères.',
          'validator.name': 'S\'il vous plaît entrer un nom.',
          'validator.number': 'S\'il vous plaît entrer un numéro.',
          'validator.notEmpty': 'C\'est un champ obligatoire.',
          'validator.amount':
              'S\'il vous plaît entrer un numéro, c\'est-à-dire 250 - Aucun symbole de dollar et sans centimes',
          'general.title': 'Comptes',
          'general.january': 'janvier',
          'general.february': 'février',
          'general.march': 'Mars',
          'general.april': 'avril',
          'general.may': 'Mai',
          'general.june': 'juin',
          'general.july': 'juillet',
          'general.august': 'août',
          'general.september': 'septembre',
          'general.october': 'Octobre',
          'general.november': 'novembre',
          'general.december': 'décembre',
          'general.total': 'Le total',
          'general.selectAll': 'Tout sélectionner',
          'general.selectowner': 'Sélectionner le propriétaire',
          'general.amount': 'Montant',
          'general.cancel': 'Annuler',
          'general.accept': 'Accepter',
          'chart.title': 'Graphique',
          'chart.monthly': 'Graphique mensuel',
          'chart.accounts': 'Comptes graphiques',
          'accounts.title': 'Comptes',
          'accounts.insert': 'Insérer',
          'accounts.delete': 'Se débarrasser de',
          'accounts.questionInsert': 'Voulez-vous insérer?',
          'accounts.questionDelete': 'Voulez-vous supprimer?',
        },
        'de': {
          'auth.signInButton': 'Einloggen',
          'auth.signUpButton': 'Registrieren',
          'auth.resetPasswordButton': 'Senden Sie das Zurücksetzen zurück',
          'auth.emailFormField': 'Email',
          'auth.passwordFormField': 'Passwort',
          'auth.nameFormField': 'Name',
          'auth.signInErrorTitle': 'Error',
          'auth.signInError': 'Anmeldefehler: E-Mail oder falsches Passwort.',
          'auth.resetPasswordLabelButton': 'Haben Sie Ihr Passwort vergessen?',
          'auth.signUpLabelButton': 'Ein Konto erstellen',
          'auth.signUpErrorTitle': 'Anmeldung gescheitert.',
          'auth.signUpError':
              'Es gab ein Problem, das sich registriert hat. Bitte versuchen Sie es später erneut.',
          'auth.signInLabelButton': 'Ein Konto haben? Einloggen.',
          'auth.resetPasswordNoticeTitle':
              'Passwort Restoration E-Mail gesendet',
          'auth.resetPasswordNotice':
              'Überprüfen Sie Ihre E-Mail und befolgen Sie die Anweisungen, um Ihr Passwort zurückzusetzen.',
          'auth.resetPasswordFailed':
              'Die Kennwortwiederherstellungs-E-Mail ist fehlgeschlagen',
          'auth.signInonResetPasswordLabelButton': 'Einloggen',
          'auth.updateUser': 'Profil-Update',
          'auth.updateUserSuccessNoticeTitle': 'Aktualisierter Benutzer.',
          'auth.updateUserSuccessNotice':
              'Benutzerinformationen erfolgreich aktualisiert.',
          'auth.updateUserEmailInUse':
              'Diese E-Mail-Adresse hat bereits ein Konto.',
          'auth.updateUserFailNotice':
              'Fehler beim Aktualisieren des Benutzers',
          'auth.enterPassword': 'Geben Sie Ihr Passwort ein.',
          'auth.cancel': 'Stornieren',
          'auth.submit': 'Senden',
          'auth.changePasswordLabelButton': 'Kennwort ändern',
          'auth.resetPasswordTitle': 'Setze dein Passwort zurück',
          'auth.updateProfileTitle': 'Profil-Update',
          'auth.wrongPasswordNoticeTitle': 'Login Fehler',
          'auth.wrongPasswordNotice':
              'Das Passwort entspricht nicht zu unseren Datensätzen.',
          'auth.unknownError': 'Unbekannter Fehler',
          'settings.title': 'die Einstellungen',
          'settings.language': 'Idiom',
          'settings.theme': 'Thema',
          'settings.signOut': 'Trennen',
          'settings.dark': 'Dunkel',
          'settings.light': 'Licht',
          'settings.system': 'System',
          'settings.updateProfile': 'Profil-Update',
          'home.title': 'Zuhause',
          'home.nameLabel': 'Name',
          'home.uidLabel': 'UID.',
          'home.emailLabel': 'Email',
          'home.adminUserLabel': 'Administrator',
          'app.title': 'Grundstartprojekt.',
          'validator.email': 'Bitte geben Sie eine gültige E-Mail-Adresse ein.',
          'validator.password':
              'Das Passwort muss mindestens 6 Zeichen betragen.',
          'validator.name': 'Bitte geben Sie einen Namen ein.',
          'validator.number': 'Bitte gebe eine Nummer ein.',
          'validator.notEmpty': 'Dies ist ein obligatorisches Feld.',
          'validator.amount':
              'Bitte geben Sie eine Nummer ein, d. H. 250 - kein Symbol für Dollar und ohne Cent',
          'general.title': 'Konten',
          'general.january': 'Januar',
          'general.february': 'Februar',
          'general.march': 'März',
          'general.april': 'April',
          'general.may': 'Kann',
          'general.june': 'Juni',
          'general.july': 'Juli',
          'general.august': 'August',
          'general.september': 'September',
          'general.october': 'Oktober',
          'general.november': 'November',
          'general.december': 'Dezember',
          'general.total': 'Gesamt',
          'general.selectAll': 'Wählen Sie Alle',
          'general.selectowner': 'Eigentümer auswählen',
          'general.amount': 'Menge',
          'general.cancel': 'Stornieren',
          'general.accept': 'Akzeptieren',
          'chart.title': 'Grafik',
          'chart.monthly': 'Monatliche Grafik.',
          'chart.accounts': 'Grafikabschlüsse',
          'accounts.title': 'Konten',
          'accounts.insert': 'Einfügen',
          'accounts.delete': 'Beseitigen, abschütteln',
          'accounts.questionInsert': 'Möchten Sie einfügen?',
          'accounts.questionDelete': 'Möchten Sie löschen?',
        },
        'hi': {
          'auth.signInButtond': 'लॉग इन करें',
          'auth.signUpButtond': 'रजिस्टर करें',
          'auth.resetPasswordButtond': 'रीसेट पासवर्ड भेजें',
          'auth.emailFormFieldd': 'ईमेल',
          'auth.passwordFormFieldd': 'कुंजिका',
          'auth.nameFormFieldd': 'नाम',
          'auth.signInErrorTitled': 'त्रुटि',
          'auth.signInErrord': 'लॉगऑन त्रुटि: ईमेल या गलत पासवर्ड।',
          'auth.resetPasswordLabelButtond': 'क्या आप अपना पासवर्ड भूल गए हैं?',
          'auth.signUpLabelButtond': 'खाता बनाएं',
          'auth.signUpErrorTitled': 'साइन अप करने में विफल रहा।',
          'auth.signUpErrord':
              'इसे पंजीकृत करने में एक समस्या थी। बाद में पुन: प्रयास करें।',
          'auth.signInLabelButtond': 'एक खाता है? लॉग इन करें।',
          'auth.resetPasswordNoticeTitled': 'पासवर्ड बहाली ईमेल भेजा गया',
          'auth.resetPasswordNoticed':
              'अपने ईमेल की समीक्षा करें और अपना पासवर्ड रीसेट करने के लिए निर्देशों का पालन करें।',
          'auth.resetPasswordFailedd': 'पासवर्ड बहाली ईमेल विफल',
          'auth.signInonResetPasswordLabelButtond': 'लॉग इन करें',
          'auth.updateUserd': 'प्रोफ़ाइल अद्यतन',
          'auth.updateUserSuccessNoticeTitled': 'अद्यतन उपयोगकर्ता।',
          'auth.updateUserSuccessNoticed':
              'उपयोगकर्ता की जानकारी सफलतापूर्वक अपडेट की गई।',
          'auth.updateUserEmailInUsed':
              'उस ईमेल पते में पहले से ही एक खाता है।',
          'auth.updateUserFailNoticed': 'उपयोगकर्ता को अद्यतन करने में त्रुटि',
          'auth.enterPasswordd': 'अपना पासवर्ड डालें।',
          'auth.canceld': 'रद्द करना',
          'auth.submitd': 'संदेश',
          'auth.changePasswordLabelButtond': 'पासवर्ड बदलें',
          'auth.resetPasswordTitled': 'अपना पासवर्ड रीसेट करें',
          'auth.updateProfileTitled': 'प्रोफ़ाइल अद्यतन',
          'auth.wrongPasswordNoticeTitled': 'लॉगिन त्रुटि',
          'auth.wrongPasswordNoticed':
              'पासवर्ड हमारे रिकॉर्ड से मेल नहीं खाता है।',
          'auth.unknownErrord': 'अज्ञात त्रुटि',
          'settings.titled': 'समायोजन',
          'settings.languaged': 'मुहावरा',
          'settings.themed': 'विषय',
          'settings.signOutd': 'डिस्कनेक्ट',
          'settings.darkd': 'अंधेरा',
          'settings.lightd': 'रोशनी',
          'settings.systemd': 'प्रणाली',
          'settings.updateProfiled': 'प्रोफ़ाइल अद्यतन',
          'home.titled': 'घर',
          'home.nameLabeld': 'नाम',
          'home.uidLabeld': 'यूआईडी।',
          'home.emailLabeld': 'ईमेल',
          'home.adminUserLabeld': 'प्रशासक',
          'app.titled': 'फर्श शुरू परियोजना',
          'validator.emaild': 'कृपया एक वैध ई - मेल एड्रेस डालें।',
          'validator.passwordd':
              'पासवर्ड में कम से कम छे कैरेक्टर होने जरूरी है।',
          'validator.named': 'कृपया एक नाम दर्ज करें।',
          'validator.numberd': 'एक संख्या दर्ज करें।',
          'validator.notEmptyd': 'यह अनिवार्य फ़ील्ड है।',
          'validator.amountd':
              'कृपया एक नंबर I.e दर्ज करें। 250 - डॉलर का कोई प्रतीक और बिना सेंट के',
          'general.titled': 'हिसाब किताब',
          'general.januaryd': 'जनवरी',
          'general.februaryd': 'फ़रवरी',
          'general.marchd': 'जुलूस',
          'general.aprild': 'अप्रैल',
          'general.mayd': 'मई',
          'general.juned': 'जून',
          'general.julyd': 'जुलाई',
          'general.augustd': 'अगस्त',
          'general.septemberd': 'सितंबर',
          'general.octoberd': 'अक्टूबर',
          'general.novemberd': 'नवंबर',
          'general.decemberd': 'दिसंबर',
          'general.totald': 'संपूर्ण',
          'general.selectAlld': 'सभी का चयन करे',
          'general.selectownerd': 'मालिक का चयन करें',
          'general.amountd': 'रकम',
          'general.canceld': 'रद्द करना',
          'general.acceptd': 'मंजूर करना',
          'chart.titled': 'ग्राफिक्स',
          'chart.monthlyd': 'मासिक ग्राफिक',
          'chart.accountsd': 'ग्राफ लेखा',
          'accounts.titled': 'हिसाब किताब',
          'accounts.insertd': 'डालने',
          'accounts.deleted': 'इससे छुटकारा पाएं',
          'accounts.questionInsertd': 'क्या आप सम्मिलित करना चाहते हैं?',
          'accounts.questionDeleted': 'क्या आप हटाना चाहते हैं?',
        },
        'pt': {
          'auth.signInButton': 'Iniciar sessão',
          'auth.signUpButton': 'Registro',
          'auth.resetPasswordButton': 'Enviar senha de reinicialização',
          'auth.emailFormField': 'Correio eletrônico',
          'auth.passwordFormField': 'Senha',
          'auth.nameFormField': 'Nome',
          'auth.signInErrorTitle': 'Erro',
          'auth.signInError': 'Erro de logon: E-mail ou senha incorreta.',
          'auth.resetPasswordLabelButton': 'Você esqueceu sua senha?',
          'auth.signUpLabelButton': 'Crie a sua conta aqui',
          'auth.signUpErrorTitle': 'Inscreva-se falhou.',
          'auth.signUpError':
              'Houve um problema registrando-o. Por favor, tente novamente mais tarde.',
          'auth.signInLabelButton': 'Ter uma conta? Iniciar sessão.',
          'auth.resetPasswordNoticeTitle':
              'E-mail de restauração de senha enviado',
          'auth.resetPasswordNotice':
              'Revise seu e-mail e siga as instruções para redefinir sua senha.',
          'auth.resetPasswordFailed': 'O e-mail de restauração de senha falhou',
          'auth.signInonResetPasswordLabelButton': 'Iniciar sessão',
          'auth.updateUser': 'Atualização do perfil.',
          'auth.updateUserSuccessNoticeTitle': 'Usuário atualizado.',
          'auth.updateUserSuccessNotice':
              'Informações do usuário atualizadas com sucesso.',
          'auth.updateUserEmailInUse':
              'Esse endereço de e-mail já tem uma conta.',
          'auth.updateUserFailNotice': 'Erro ao atualizar o usuário',
          'auth.enterPassword': 'Coloque sua senha.',
          'auth.cancel': 'Cancelar',
          'auth.submit': 'Mandar',
          'auth.changePasswordLabelButton': 'Alterar a senha',
          'auth.resetPasswordTitle': 'Redefinir sua senha',
          'auth.updateProfileTitle': 'Atualização do perfil.',
          'auth.wrongPasswordNoticeTitle': 'Erro de login.',
          'auth.wrongPasswordNotice':
              'A senha não corresponde aos nossos registros.',
          'auth.unknownError': 'Erro desconhecido',
          'settings.title': 'Definições',
          'settings.language': 'Idioma',
          'settings.theme': 'Tema',
          'settings.signOut': 'desconectar',
          'settings.dark': 'Escuro',
          'settings.light': 'Luz',
          'settings.system': 'Sistema',
          'settings.updateProfile': 'Atualização do perfil.',
          'home.title': 'Casa',
          'home.nameLabel': 'Nome',
          'home.uidLabel': 'Uid.',
          'home.emailLabel': 'Correio eletrônico',
          'home.adminUserLabel': 'Administrador',
          'app.title': 'Projeto de início do chão',
          'validator.email': 'Por favor insira um endereço de e-mail válido.',
          'validator.password': 'A senha deve ter pelo menos 6 caracteres.',
          'validator.name': 'Por favor, insira um nome.',
          'validator.number': 'Por favor, coloque um numero.',
          'validator.notEmpty': 'Este é um campo obrigatório.',
          'validator.amount':
              'Por favor, insira um número i.e. 250 - Nenhum símbolo de dólar e sem centavos',
          'general.title': 'Contas',
          'general.january': 'Janeiro',
          'general.february': 'fevereiro',
          'general.march': 'Março',
          'general.april': 'abril',
          'general.may': 'Maio',
          'general.june': 'Junho',
          'general.july': 'julho',
          'general.august': 'agosto',
          'general.september': 'setembro',
          'general.october': 'Outubro',
          'general.november': 'novembro',
          'general.december': 'dezembro',
          'general.total': 'Total',
          'general.selectAll': 'Selecionar tudo',
          'general.selectowner': 'Selecione Proprietário',
          'general.amount': 'Resultar',
          'general.cancel': 'Cancelar',
          'general.accept': 'Aceitar',
          'chart.title': 'Gráficos',
          'chart.monthly': 'Gráfico mensal',
          'chart.accounts': 'Contas de gráfico',
          'accounts.title': 'Contas',
          'accounts.insert': 'Inserir',
          'accounts.delete': 'Livrar-se de',
          'accounts.questionInsert': 'Você quer inserir?',
          'accounts.questionDelete': 'Você quer deletar?',
        },
        'zh': {
          'auth.signInButton': '登录',
          'auth.signUpButton': '登记',
          'auth.resetPasswordButton': '发送重置密码',
          'auth.emailFormField': '电子邮件',
          'auth.passwordFormField': '密码',
          'auth.nameFormField': '名称',
          'auth.signInErrorTitle': '错误',
          'auth.signInError': '登录错误：密码电子邮件或不正确。',
          'auth.resetPasswordLabelButton': '你忘记密码了吗？',
          'auth.signUpLabelButton': '创建一个帐户',
          'auth.signUpErrorTitle': '注册失败。',
          'auth.signUpError': '注册它有问题。请稍后再试。',
          'auth.signInLabelButton': '有一个账户？登录。',
          'auth.resetPasswordNoticeTitle': '密码恢复电子邮件发送',
          'auth.resetPasswordNotice': '查看您的电子邮件并按照说明重置密码。',
          'auth.resetPasswordFailed': '密码恢复电子邮件失败',
          'auth.signInonResetPasswordLabelButton': '登录',
          'auth.updateUser': '个人资料更新',
          'auth.updateUserSuccessNoticeTitle': '更新的用户。',
          'auth.updateUserSuccessNotice': '用户信息成功更新。',
          'auth.updateUserEmailInUse': '该电子邮件地址已经有一个帐户。',
          'auth.updateUserFailNotice': '更新用户时出错',
          'auth.enterPassword': '输入您的密码。',
          'auth.cancel': '取消',
          'auth.submit': '发送',
          'auth.changePasswordLabelButton': '更改密码',
          'auth.resetPasswordTitle': '重置你的密码',
          'auth.updateProfileTitle': '个人资料更新',
          'auth.wrongPasswordNoticeTitle': '登录错误',
          'auth.wrongPasswordNotice': '密码与我们的记录不匹配。',
          'auth.unknownError': '未知错误',
          'settings.title': '设置',
          'settings.language': '成语',
          'settings.theme': '主题',
          'settings.signOut': '断开',
          'settings.dark': '黑暗的',
          'settings.light': '光',
          'settings.system': '系统',
          'settings.updateProfile': '个人资料更新',
          'home.title': '家',
          'home.nameLabel': '名称',
          'home.uidLabel': 'UID。',
          'home.emailLabel': '电子邮件',
          'home.adminUserLabel': '行政人员',
          'app.title': '地板开始项目',
          'validator.email': '请输入有效的电子邮件地址。',
          'validator.password': '密码必须至少为6个字符。',
          'validator.name': '请输入名称。',
          'validator.number': '请输入一个号码。',
          'validator.notEmpty': '这是一个强制性领域。',
          'validator.amount': '请输入一个号码i.e. 250  - 没有美元和没有美分的象征',
          'general.title': '账户',
          'general.january': '一月',
          'general.february': '二月',
          'general.march': '行进',
          'general.april': '四月',
          'general.may': '可能',
          'general.june': '六月',
          'general.july': '七月',
          'general.august': '八月',
          'general.september': '九月',
          'general.october': '十月',
          'general.november': '十一月',
          'general.december': '十二月',
          'general.total': '全部的',
          'general.selectAll': '全选',
          'general.selectowner': '选择所有者',
          'general.amount': '数量',
          'general.cancel': '取消',
          'general.accept': '接受',
          'chart.title': '图形',
          'chart.monthly': '每月图形',
          'chart.accounts': '图表帐户',
          'accounts.title': '账户',
          'accounts.insert': '插',
          'accounts.delete': '摆脱',
          'accounts.questionInsert': '你想插入吗？',
          'accounts.questionDelete': '你想删除吗？',
        },
        'ja': {
          'auth.signInButton': 'ログイン',
          'auth.signUpButton': '登録',
          'auth.resetPasswordButton': 'リセットパスワードを送信します',
          'auth.emailFormField': 'Eメール',
          'auth.passwordFormField': 'パスワード',
          'auth.nameFormField': '名前',
          'auth.signInErrorTitle': 'エラー',
          'auth.signInError': 'ログオンエラー：Eメールまたは誤ったパスワード。',
          'auth.resetPasswordLabelButton': 'パスワードを忘れた？',
          'auth.signUpLabelButton': 'アカウントを作成する',
          'auth.signUpErrorTitle': 'サインアップに失敗しました。',
          'auth.signUpError': 'それを登録する問題がありました。後でもう一度やり直してください。',
          'auth.signInLabelButton': 'アカウントを持っています？ログイン。',
          'auth.resetPasswordNoticeTitle': 'パスワード復元Eメール送信',
          'auth.resetPasswordNotice': '電子メールを確認して、指示に従ってパスワードをリセットしてください。',
          'auth.resetPasswordFailed': 'パスワードの復元のEメールに失敗しました',
          'auth.signInonResetPasswordLabelButton': 'ログイン',
          'auth.updateUser': 'プロファイルの更新',
          'auth.updateUserSuccessNoticeTitle': '更新されました。',
          'auth.updateUserSuccessNotice': 'ユーザー情報が正常に更新されました。',
          'auth.updateUserEmailInUse': 'そのEメールアドレスはすでにアカウントを持っています。',
          'auth.updateUserFailNotice': 'ユーザーの更新エラー',
          'auth.enterPassword': 'パスワードを入力してください。',
          'auth.cancel': 'キャンセル',
          'auth.submit': '送ります',
          'auth.changePasswordLabelButton': 'パスワードを変更する',
          'auth.resetPasswordTitle': 'あなたのパスワードをリセット',
          'auth.updateProfileTitle': 'プロファイルの更新',
          'auth.wrongPasswordNoticeTitle': 'ログインエラー',
          'auth.wrongPasswordNotice': 'パスワードは私たちの記録と一致しません。',
          'auth.unknownError': '不明なエラー',
          'settings.title': '設定',
          'settings.language': '熟語',
          'settings.theme': 'テーマ',
          'settings.signOut': '切断する',
          'settings.dark': '闇',
          'settings.light': '光',
          'settings.system': 'システム',
          'settings.updateProfile': 'プロファイルの更新',
          'home.title': '在宅',
          'home.nameLabel': '名前',
          'home.uidLabel': 'UID。',
          'home.emailLabel': 'Eメール',
          'home.adminUserLabel': '管理者',
          'app.title': '床開始プロジェクト',
          'validator.email': '有効なメールアドレスを入力してください。',
          'validator.password': 'パスワードは6文字以上でなければなりません。',
          'validator.name': '名前を入力してください。',
          'validator.number': '数字を入力してください。',
          'validator.notEmpty': 'これは必須のフィールドです。',
          'validator.amount': 'すなわち数字を入力してください250  - ドルのシンボルはセントなしではありません',
          'general.title': 'アカウント',
          'general.january': '1月',
          'general.february': '2月',
          'general.march': '行進',
          'general.april': '4月',
          'general.may': '五月',
          'general.june': '六月',
          'general.july': 'j',
          'general.august': '八重',
          'general.september': '9月',
          'general.october': '10月',
          'general.november': '11月',
          'general.december': 'dec dec',
          'general.total': '合計',
          'general.selectAll': 'すべて選択',
          'general.selectowner': '所有者を選択してください',
          'general.amount': '量',
          'general.cancel': 'キャンセル',
          'general.accept': '受け入れるために',
          'chart.title': 'グラフィック',
          'chart.monthly': '月刊グラフィック',
          'chart.accounts': 'グラフアカウント',
          'accounts.title': 'アカウント',
          'accounts.insert': 'インサート',
          'accounts.delete': '取り除く',
          'accounts.questionInsert': '挿入しますか？',
          'accounts.questionDelete': '削除しますか？',
        },
        'ru': {
          'auth.signInButton': 'Авторизоваться',
          'auth.signUpButton': 'регистр',
          'auth.resetPasswordButton': 'Отправить пароль сброса',
          'auth.emailFormField': 'Электронное письмо',
          'auth.passwordFormField': 'Пароль',
          'auth.nameFormField': 'Имя',
          'auth.signInErrorTitle': 'Ошибка',
          'auth.signInError':
              'Ошибка входа в систему: электронная почта или неправильный пароль.',
          'auth.resetPasswordLabelButton': 'Вы забыли свой пароль?',
          'auth.signUpLabelButton': 'Завести аккаунт',
          'auth.signUpErrorTitle': 'Регистрация прошла неудачно.',
          'auth.signUpError':
              'Была проблема, зарегистрировавшая ее. Пожалуйста, повторите попытку позже.',
          'auth.signInLabelButton': 'Иметь аккаунт? Авторизоваться.',
          'auth.resetPasswordNoticeTitle':
              'Восстановление пароля отправлено письмо',
          'auth.resetPasswordNotice':
              'Просмотрите свою электронную почту и следуйте инструкциям для сброса пароля.',
          'auth.resetPasswordFailed':
              'Восстановление пароля по электронной почте не удалось',
          'auth.signInonResetPasswordLabelButton': 'Авторизоваться',
          'auth.updateUser': 'Обновление профиля',
          'auth.updateUserSuccessNoticeTitle': 'Обновленный пользователь.',
          'auth.updateUserSuccessNotice':
              'Информация о пользователе успешно обновляется.',
          'auth.updateUserEmailInUse':
              'Этот адрес электронной почты уже имеет учетную запись.',
          'auth.updateUserFailNotice': 'Ошибка обновления пользователя',
          'auth.enterPassword': 'Введите свой пароль.',
          'auth.cancel': 'Отмена',
          'auth.submit': 'послать',
          'auth.changePasswordLabelButton': 'Измени пароль',
          'auth.resetPasswordTitle': 'Сбросить пароль',
          'auth.updateProfileTitle': 'Обновление профиля',
          'auth.wrongPasswordNoticeTitle': 'Ошибка входа',
          'auth.wrongPasswordNotice': 'Пароль не соответствует нашим записям.',
          'auth.unknownError': 'Неизвестная ошибка',
          'settings.title': 'Настройки',
          'settings.language': 'Idiom.',
          'settings.theme': 'Тема',
          'settings.signOut': 'Отключить',
          'settings.dark': 'Темный',
          'settings.light': 'Свет',
          'settings.system': 'Система',
          'settings.updateProfile': 'Обновление профиля',
          'home.title': 'Дом',
          'home.nameLabel': 'Имя',
          'home.uidLabel': 'UID.',
          'home.emailLabel': 'Электронное письмо',
          'home.adminUserLabel': 'Администратор',
          'app.title': 'Проект начала пола',
          'validator.email':
              'Пожалуйста, введите действительный адрес электронной почты.',
          'validator.password': 'Пароль должен быть не менее 6 символов.',
          'validator.name': 'Пожалуйста, введите имя.',
          'validator.number': 'Пожалуйста, введите номер.',
          'validator.notEmpty': 'Это обязательное поле.',
          'validator.amount':
              'Пожалуйста, введите номер I.E. 250 - нет символа доллара и без центов',
          'general.title': 'учетные записи',
          'general.january': 'Январь',
          'general.february': 'Февраль',
          'general.march': 'маршировать',
          'general.april': 'апреля',
          'general.may': 'Может',
          'general.june': 'июнь',
          'general.july': 'июль',
          'general.august': 'август',
          'general.september': 'сентябрь',
          'general.october': 'Октябрь',
          'general.november': 'Ноябрь',
          'general.december': 'Декабрь',
          'general.total': 'Общее',
          'general.selectAll': 'Выбрать все',
          'general.selectowner': 'Выберите владельца',
          'general.amount': 'Количество',
          'general.cancel': 'Отмена',
          'general.accept': 'Принять',
          'chart.title': 'Графика',
          'chart.monthly': 'Ежемесячная графика',
          'chart.accounts': 'Графические счета',
          'accounts.title': 'учетные записи',
          'accounts.insert': 'Вставлять',
          'accounts.delete': 'Избавиться от',
          'accounts.questionInsert': 'Вы хотите вставить?',
          'accounts.questionDelete': 'Вы хотите удалить?',
        },
      };
}
